name: Security Scanning Workflow

on:
  push:
    branches:
      - main

jobs:
  owasp_zap_scan:
    name: DAST/OWASP ZAP BASELINE SCAN
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: DAST/OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          exit_zero: true

  bandit_docker:
    name: Bandit Security Scan (Docker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt-get update -y
          sudo apt-get install python3 -y
          sudo apt-get install python3-pip -y
          python3 -m pip install bandit

      - name: Run Bandit Security Scan
        run: |
          # Replace this line with the Bandit scan command for your project
          bandit -r .